// src/types/projectTypes.ts

/**
 * Represents a single scene within a storyboard, as generated by the initial LLM
 * for planning the overall video.
 */
export interface IStoryboardScene {
  scene_title: string;
  narration: string;
  visual_description: string;
}

/**
 * Parameters passed to the LLM when generating Manim code for a specific scene.
 */
export interface ILLMCodeGenerationParams {
  narration: string;
  visual_description: string;
  scene_number: number;
  total_scenes: number;
  topic: string; // The overall topic of the video, derived from user's initial idea
  previousSceneContext?: string; // Optional: Brief description of what happened in the previous scene
}

/**
 * Represents the output and details of a single processed (rendered) scene.
 */
export interface ISceneOutput {
  scene_number: number;
  scene_title: string;
  narration: string; // Retain narration for potential TTS or display
  manim_code_generated?: string; // The Manim code that was generated (for debugging/potential edit)
  video_url?: string;            // URL to the rendered video snippet for this scene
  audio_url?: string;            // (Future) URL to the TTS audio for this scene's narration
  status: 'pending' | 'processing' | 'completed' | 'failed';
  error_message?: string;        // Error message if processing this specific scene failed
}

/**
 * Represents the overall data for a user's project, including all its scenes.
 */
export interface IProjectData {
  projectId: string;
  userIdea?: string; // The original idea that initiated the project
  storyboard?: IStoryboardScene[]; // The generated storyboard (array of scenes)
  scenes: ISceneOutput[]; // Array of processed scene outputs
  status: 'pending' | 'processing' | 'completed' | 'partially_completed' | 'failed';
  final_video_url?: string; // (Future) URL to the fully stitched final video
  userId?: string; // (Future) To associate project with a user
  createdAt?: Date;
  updatedAt?: Date;
}


// --- Request Body & Parameter Types for API Controllers ---

/**
 * Expected request body for initiating a new project.
 */
export interface ICreateProjectRequestBody {
  userIdea: string;
  // userId?: string; // If/when you add user authentication
}

/**
 * Expected request body for generating video from a storyboard.
 */
export interface IGenerateVideoRequestBody {
  storyboard: IStoryboardScene[]; // The storyboard to generate video from
  userIdea?:string;
  // You might add other options here later, like output quality, TTS voice, etc.
}

/**
 * Expected URL parameters for routes that include a projectId.
 */
export interface IProjectParams {
  projectId: string;
}